import PDFDocument from 'pdfkit';

const pdfkitFontPath = require('pdfkit').FontPath;

interface ReportData {
  date?: string;
  startDate?: string;
  endDate?: string;
  revenue?: number;
  orders?: number;
  aov?: number;
  topProducts?: Array<{ name: string; orders: number; revenue: number }>;
  totalRevenue?: number;
  totalOrders?: number;
  avgDailyRevenue?: number;
  peakDays?: string[];
  growthStrategy?: {
    revenue_target: string;
    growth_rate: string;
    key_levers: string[];
  };
  inventoryAlerts?: Array<{ product: string; stock: number; daysLeft: number }>;
}

function formatCurrency(amount: number): string {
  if (amount >= 10000000) {
    return `₹${(amount / 10000000).toFixed(2)} Cr`;
  } else if (amount >= 100000) {
    return `₹${(amount / 100000).toFixed(2)} L`;
  } else if (amount >= 1000) {
    return `₹${(amount / 1000).toFixed(2)} K`;
  }
  return `₹${amount.toFixed(0)}`;
}

export function generateDailyPDF(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({ 
        margin: 50,
        size: 'A4',
        info: {
          Title: 'Nirvaah Daily Report',
          Author: 'Nirvaah AI',
        }
      });
      
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(28).fillColor('#1a1a1a').text('NIRVAAH', { align: 'center' });
      doc.fontSize(12).fillColor('#cfa15f').text('DAILY PERFORMANCE REPORT', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).fillColor('#666').text(`Date: ${data.date || new Date().toLocaleDateString()}`, { align: 'center' });
      
      // Divider
      doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ddd').stroke();
      doc.moveDown(2);

      // Key Metrics
      doc.fontSize(14).fillColor('#1a1a1a').text('Performance Overview', { underline: true });
      doc.moveDown();

      const metrics = [
        { label: 'Total Revenue', value: formatCurrency(data.revenue || 0) },
        { label: 'Total Orders', value: (data.orders || 0).toString() },
        { label: 'Average Order Value', value: formatCurrency(data.aov || 0) },
      ];

      metrics.forEach(m => {
        doc.fontSize(11).fillColor('#666').text(m.label, 50, doc.y, { continued: false });
        doc.fontSize(14).fillColor('#1a1a1a').text(m.value, 200, doc.y - 14);
      });

      doc.moveDown(2);

      // Top Products
      if (data.topProducts && data.topProducts.length > 0) {
        doc.fontSize(14).fillColor('#1a1a1a').text('Top Selling Products', { underline: true });
        doc.moveDown();

        const tableTop = doc.y;
        doc.fontSize(10).fillColor('#666');
        doc.text('Product', 50, tableTop);
        doc.text('Orders', 300, tableTop);
        doc.text('Revenue', 400, tableTop);

        doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).strokeColor('#eee').stroke();

        let yPos = tableTop + 25;
        data.topProducts.forEach((p, i) => {
          const bgColor = i % 2 === 0 ? '#f9f9f9' : '#fff';
          doc.rect(50, yPos - 5, 500, 20).fill(bgColor);
          doc.fillColor('#1a1a1a').fontSize(10).text(p.name, 55, yPos);
          doc.fillColor('#666').text(p.orders.toString(), 300, yPos);
          doc.fillColor('#cfa15f').text(formatCurrency(p.revenue || 0), 400, yPos);
          yPos += 20;
        });
      }

      // Footer
      doc.fontSize(8).fillColor('#999').text(
        'Generated by Nirvaah AI Insights | Report sent to registered email',
        50,
        750,
        { align: 'center' }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export function generateWeeklyPDF(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({ margin: 50 });
      
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(28).fillColor('#1a1a1a').text('NIRVAAH', { align: 'center' });
      doc.fontSize(12).fillColor('#cfa15f').text('WEEKLY PERFORMANCE REPORT', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).fillColor('#666').text(
        `Period: ${data.startDate || ''} to ${data.endDate || ''}`,
        { align: 'center' }
      );
      
      doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ddd').stroke();
      doc.moveDown(2);

      // Key Metrics
      doc.fontSize(14).fillColor('#1a1a1a').text('Week at a Glance', { underline: true });
      doc.moveDown();

      const metrics = [
        { label: 'Total Revenue', value: formatCurrency(data.totalRevenue || 0) },
        { label: 'Total Orders', value: (data.totalOrders || 0).toString() },
        { label: 'Daily Average', value: formatCurrency(data.avgDailyRevenue || 0) },
        { label: 'Peak Days', value: data.peakDays?.join(', ') || 'Weekend' },
      ];

      metrics.forEach(m => {
        doc.fontSize(11).fillColor('#666').text(m.label, 50, doc.y, { continued: false });
        doc.fontSize(14).fillColor('#1a1a1a').text(m.value, 220, doc.y - 14);
        doc.moveDown(0.5);
      });

      doc.moveDown(2);

      // Growth Strategy
      if (data.growthStrategy) {
        doc.fontSize(14).fillColor('#1a1a1a').text('Growth Strategy', { underline: true });
        doc.moveDown();
        doc.fontSize(11).fillColor('#666').text('Next Week Targets:', 50, doc.y);
        doc.moveDown();
        
        doc.fontSize(11).fillColor('#1a1a1a');
        doc.text(`• Revenue Target: ${data.growthStrategy.revenue_target}`, { indent: 20 });
        doc.text(`• Growth Rate: ${data.growthStrategy.growth_rate}`, { indent: 20 });
        doc.text(`• Key Levers: ${data.growthStrategy.key_levers?.join(', ') || 'N/A'}`, { indent: 20 });
      }

      // Inventory Alerts
      if (data.inventoryAlerts && data.inventoryAlerts.length > 0) {
        doc.moveDown(2);
        doc.fontSize(14).fillColor('#1a1a1a').text('Inventory Alerts', { underline: true });
        doc.moveDown();

        data.inventoryAlerts.forEach(alert => {
          const alertColor = alert.daysLeft <= 5 ? '#e74c3c' : '#f39c12';
          doc.fontSize(10).fillColor(alertColor);
          doc.text(`⚠ ${alert.product}: ${alert.stock} units (${alert.daysLeft} days left)`, 50, doc.y);
        });
      }

      // Footer
      doc.fontSize(8).fillColor('#999').text(
        'Generated by Nirvaah AI Insights | Weekly Strategic Report',
        50,
        750,
        { align: 'center' }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export function generateMonthlyPDF(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(32).fillColor('#1a1a1a').text('NIRVAAH', { align: 'center' });
      doc.fontSize(14).fillColor('#cfa15f').text('MONTHLY BUSINESS REPORT', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).fillColor('#666').text(
        `Month: ${data.startDate || ''} to ${data.endDate || ''}`,
        { align: 'center' }
      );
      
      doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ddd').stroke();
      doc.moveDown(2);

      // Executive Summary
      doc.fontSize(16).fillColor('#1a1a1a').text('Executive Summary', { underline: true });
      doc.moveDown();

      const metrics = [
        { label: 'Total Revenue', value: formatCurrency(data.totalRevenue || 0), highlight: true },
        { label: 'Total Orders', value: (data.totalOrders || 0).toString() },
      ];

      metrics.forEach(m => {
        doc.fontSize(12).fillColor('#666').text(m.label + ':', 50, doc.y, { continued: false });
        if (m.highlight) {
          doc.fontSize(20).fillColor('#cfa15f').text(m.value, 200, doc.y - 12);
        } else {
          doc.fontSize(16).fillColor('#1a1a1a').text(m.value, 200, doc.y - 8);
        }
        doc.moveDown(0.5);
      });

      doc.moveDown(2);

      // Growth Strategy
      if (data.growthStrategy) {
        doc.fontSize(14).fillColor('#1a1a1a').text('Growth Strategy & Targets', { underline: true });
        doc.moveDown();
        
        doc.fontSize(11).fillColor('#1a1a1a');
        doc.text(`Revenue Target: ${data.growthStrategy.revenue_target}`, { indent: 20 });
        doc.text(`Growth Rate: ${data.growthStrategy.growth_rate}`, { indent: 20 });
        doc.moveDown();
        doc.fillColor('#666').text('Key Levers:', 50, doc.y);
        (data.growthStrategy.key_levers || []).forEach(lever => {
          doc.text(`• ${lever}`, { indent: 30 });
        });
      }

      // Inventory Alerts
      if (data.inventoryAlerts && data.inventoryAlerts.length > 0) {
        doc.moveDown(2);
        doc.fontSize(14).fillColor('#1a1a1a').text('Inventory Status', { underline: true });
        doc.moveDown();

        data.inventoryAlerts.forEach(alert => {
          const color = alert.daysLeft <= 5 ? '#e74c3c' : alert.daysLeft <= 10 ? '#f39c12' : '#27ae60';
          doc.fontSize(10).fillColor(color);
          doc.text(`• ${alert.product}: ${alert.stock} units remaining`, 50, doc.y);
        });
      }

      // Marketing Recommendations
      doc.moveDown(2);
      doc.fontSize(14).fillColor('#1a1a1a').text('Strategic Recommendations', { underline: true });
      doc.moveDown();
      doc.fontSize(10).fillColor('#666');
      doc.text('This month\'s strategic priorities have been generated by AI analysis of your business data.');
      doc.text('Review the AI Insights tab in your admin panel for detailed recommendations.');

      // Footer
      doc.fontSize(8).fillColor('#999').text(
        'Generated by Nirvaah AI Insights | Confidential - For Internal Use Only',
        50,
        780,
        { align: 'center' }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}